In [1]:
import pandas as pd

In [2]:
import streamlit as st

In [3]:
data = pd.read_csv('DSZ.csv',header=0, index_col = False)

In [4]:
data

,Timestamp,What is your age?,Gender,Country of current residence,What are you currently doing?,What is the highest education level attained? (or to be attained in the next 12 months),In what field is your highest attained academic programme?,What field best characterises the company you are working for? (If employed),What is your current role/title? (If employed),Are you working in a data-related capacity?,...,What is your primary programming language for work in data?,What other tools do you use for data?,(If *Other* in previous question) Which other tools do you use?,How long have you been writing code/doing programmatic data analysis?,Do you use any specialised hardware for data science?,Which specialised hardware do you use?,Which of the following is part of your skillset (comfortable in doing)?,Which of the following do you hope to achieve in the next 12 months?,What has been your biggest obstacle in doing your work in data/practicing as a data profession/pursuing a journey in data?,What are the initiatives Data Science Zimbabwe should undertake to benefit you more as a data science community member?
0,5/3/2022 16:26:34,18-25,M,Zimbabwe,Unemployed,Bachelors,agriculture economics,NaN,NaN,No,...,"Python, R, SPSS/SAS",Excel,NaN,<1 year,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),internet,open more apprenticeship for data science
1,5/3/2022 16:30:12,>25,M,Zimbabwe,Formally employed,Bachelors,Software Engineering,Telecommunications,Software Developer,Sometimes,...,"Python, Other","Excel, Other",SQL,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Relevent Datasets,Competitions for solving local problems.
2,5/3/2022 16:42:31,18-25,M,Zimbabwe,Formally employed,Bachelors,IT,Retail,IT Tech,No,...,"Python, R",Excel,Power BI,<1 year,No,NaN,"Data visualisation, Computer Vision, Reinforce...",Certifications (online courses),Availability of local datasets,Training and seminars
3,5/3/2022 16:48:45,18-25,M,Zimbabwe,University/College,GCE O/A Level,A level Sciences,NaN,NaN,Sometimes,...,Python,Excel,NaN,1 - 5 years,No,NaN,Computer Vision,Certifications (online courses),Time management,Offer course with certification
4,5/3/2022 17:13:37,>25,M,Zimbabwe,Formally employed,Bachelors,Computer Information Systems,Solution Orientation,Software Engineer,No,...,Python,Knime/Weka/RapidMiner,NaN,>5 years,No,NaN,"Data visualisation, NLP",Certifications (online courses),Opportunities,Open source projects
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,5/28/2022 14:12:10,18-25,F,Zimbabwe,University/College,Bachelors,Accounting,Auditing,Audit intern,No,...,R,Excel,NaN,1 - 5 years,No,NaN,Data visualisation,Certifications (online courses),Teaching myself,Seminars or workshops and invite beginners (li...
72,6/1/2022 1:27:43,18-25,M,Zimbabwe,University/College,Bachelors,Informatics,Health,Systems Administrator,No,...,Python,Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Computer Vision, NLP, Tabu...",Certifications (online courses),Hardware Resources and Lack of Finances for Ce...,creating partnerships that may make certificat...
73,6/1/2022 13:21:22,>25,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Commerce,NGO,Province administration,Yes,...,SPSS/SAS,Excel,NaN,<1 year,No,NaN,Tabular data,Certifications (online courses),Skill,"Offer more courses, bootcamps and meetups"
74,6/5/2022 23:21:52,>25,F,Zimbabwe,Unemployed,Bachelors,Mathematics,NaN,NaN,No,...,Python,Excel,NaN,<1 year,No,NaN,Data visualisation,Certifications (online courses),Having to take time out for health reasons but...,Please keep sharing links to allow us to incre...
75,6/6/2022 9:13:05,18-25,F,Zimbabwe,Formally employed,Bachelors,Statistics,Banking,Customer service advisor / Teller,No,...,Python,Other,SQL,<1 year,No,NaN,NaN,Certifications (online courses),Time,"Conduct trainings for data scientist, Conduct ..."

In [5]:
print(data.columns.tolist())

['Timestamp', 'What is your age?', 'Gender', 'Country of current residence', 'What are you currently doing?', 'What is the highest education level attained? (or to be attained in the next 12 months)', 'In what field is your highest attained academic programme?', 'What field best characterises the company you are working for? (If employed)', 'What is your current role/title? (If employed)', 'Are you working in a data-related capacity? ', 'Does your company incorporate any data science, machine learning or AI methods in their business?', 'What route have you taken/are taking to be a data professional?', 'What is your primary programming language for work in data?', 'What other tools do you use for data?', '(If *Other* in previous question) Which other tools do you use?', 'How long have you been writing code/doing programmatic data analysis?', 'Do you use any specialised hardware for data science?', 'Which specialised hardware do you use?', 'Which of the following is part of your skillset (comfortable in doing)?', 'Which of the following do you hope to achieve in the next 12 months?', 'What has been your biggest obstacle in doing your work in data/practicing as a data profession/pursuing a journey in data? ', 'What are the initiatives Data Science Zimbabwe should undertake to benefit you more as a data science community member?']

In [6]:
data.drop('Timestamp',axis = 1,inplace= True)

In [7]:
data.rename(columns={'What is your age?':'Age','Country of current residence':'Country','What are you currently doing?':'Ocupation','What is the highest education level attained? (or to be attained in the next 12 months)':'HighestEducationLevel','In what field is your highest attained academic programme?':'Field','What field best characterises the company you are working for? (If employed)':'Company','What is your current role/title? (If employed)':'Role','Are you working in a data-related capacity?':'WorkingWithData','Does your company incorporate any data science, machine learning or AI methods in their business?':'AI/ML/Ds','What route have you taken/are taking to be a data professional?':'route','What is your primary programming language for work in data?':'MainLanguage','What other tools do you use for data?':'Tools','(If *Other* in previous question) Which other tools do you use?':'Other', 'How long have you been writing code/doing programmatic data analysis?':'CodingPeriod','Do you use any specialised hardware for data science?':'SpecialisedHardware','Which specialised hardware do you use':'Hardware','Which of the following is part of your skillset (comfortable in doing)?':'skillset','Which of the following do you hope to achieve in the next 12 months?':'Goals','What has been your biggest obstacle in doing your work in data/practicing as a data profession/pursuing a journey in data?':'obstacle','What are the initiatives Data Science Zimbabwe should undertake to benefit you more as a data science community member?':'IntiativesDSZToTake'},inplace = True)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 21 columns):
 #   Column                                                                                                                       Non-Null Count  Dtype
---  ------                                                                                                                       --------------  -----
 0   Age                                                                                                                          76 non-null     object
 1   Gender                                                                                                                       76 non-null     object
 2   Country                                                                                                                      76 non-null     object
 3   Ocupation                                                                                                                    76 non-null     object
 4   HighestEducationLevel                                                                                                        76 non-null     object
 5   Field                                                                                                                        72 non-null     object
 6   Company                                                                                                                      62 non-null     object
 7   Role                                                                                                                         61 non-null     object
 8   Are you working in a data-related capacity?                                                                                  72 non-null     object
 9   AI/ML/Ds                                                                                                                     67 non-null     object
 10  route                                                                                                                        76 non-null     object
 11  MainLanguage                                                                                                                 76 non-null     object
 12  Tools                                                                                                                        75 non-null     object
 13  Other                                                                                                                        23 non-null     object
 14  CodingPeriod                                                                                                                 75 non-null     object
 15  SpecialisedHardware                                                                                                          75 non-null     object
 16  Which specialised hardware do you use?                                                                                       9 non-null      object
 17  skillset                                                                                                                     73 non-null     object
 18  Goals                                                                                                                        76 non-null     object
 19  What has been your biggest obstacle in doing your work in data/practicing as a data profession/pursuing a journey in data?   74 non-null     object
 20  IntiativesDSZToTake                                                                                                          59 non-null     object
dtypes: object(21)
memory usage: 12.6+ KB

In [9]:
data

,Age,Gender,Country,Ocupation,HighestEducationLevel,Field,Company,Role,Are you working in a data-related capacity?,AI/ML/Ds,...,MainLanguage,Tools,Other,CodingPeriod,SpecialisedHardware,Which specialised hardware do you use?,skillset,Goals,What has been your biggest obstacle in doing your work in data/practicing as a data profession/pursuing a journey in data?,IntiativesDSZToTake
0,18-25,M,Zimbabwe,Unemployed,Bachelors,agriculture economics,NaN,NaN,No,No,...,"Python, R, SPSS/SAS",Excel,NaN,<1 year,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),internet,open more apprenticeship for data science
1,>25,M,Zimbabwe,Formally employed,Bachelors,Software Engineering,Telecommunications,Software Developer,Sometimes,Yes,...,"Python, Other","Excel, Other",SQL,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Relevent Datasets,Competitions for solving local problems.
2,18-25,M,Zimbabwe,Formally employed,Bachelors,IT,Retail,IT Tech,No,Yes,...,"Python, R",Excel,Power BI,<1 year,No,NaN,"Data visualisation, Computer Vision, Reinforce...",Certifications (online courses),Availability of local datasets,Training and seminars
3,18-25,M,Zimbabwe,University/College,GCE O/A Level,A level Sciences,NaN,NaN,Sometimes,NaN,...,Python,Excel,NaN,1 - 5 years,No,NaN,Computer Vision,Certifications (online courses),Time management,Offer course with certification
4,>25,M,Zimbabwe,Formally employed,Bachelors,Computer Information Systems,Solution Orientation,Software Engineer,No,Yes,...,Python,Knime/Weka/RapidMiner,NaN,>5 years,No,NaN,"Data visualisation, NLP",Certifications (online courses),Opportunities,Open source projects
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,18-25,F,Zimbabwe,University/College,Bachelors,Accounting,Auditing,Audit intern,No,No,...,R,Excel,NaN,1 - 5 years,No,NaN,Data visualisation,Certifications (online courses),Teaching myself,Seminars or workshops and invite beginners (li...
72,18-25,M,Zimbabwe,University/College,Bachelors,Informatics,Health,Systems Administrator,No,No,...,Python,Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Computer Vision, NLP, Tabu...",Certifications (online courses),Hardware Resources and Lack of Finances for Ce...,creating partnerships that may make certificat...
73,>25,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Commerce,NGO,Province administration,Yes,Yes,...,SPSS/SAS,Excel,NaN,<1 year,No,NaN,Tabular data,Certifications (online courses),Skill,"Offer more courses, bootcamps and meetups"
74,>25,F,Zimbabwe,Unemployed,Bachelors,Mathematics,NaN,NaN,No,No,...,Python,Excel,NaN,<1 year,No,NaN,Data visualisation,Certifications (online courses),Having to take time out for health reasons but...,Please keep sharing links to allow us to incre...
75,18-25,F,Zimbabwe,Formally employed,Bachelors,Statistics,Banking,Customer service advisor / Teller,No,No,...,Python,Other,SQL,<1 year,No,NaN,NaN,Certifications (online courses),Time,"Conduct trainings for data scientist, Conduct ..."

In [10]:
data['Country'].unique()

array(['Zimbabwe', 'Zimbabwe ', 'zimbabwe', 'US', 'SA', 'ZImbabwe',
       'Zimbabwe - sadly', 'Scotland ', 'Equatorial Guinea ',
       'South Africa '], dtype=object)

In [11]:
data['route'].unique()

array(['Self-taught/Bootcamp (including MOOCs e.g Datacamp, Alison, Dataquest, Coursera), University program in another discipline (e.g Economics, Monitoring and Evaluation etc)',
       'Self-taught/Bootcamp (including MOOCs e.g Datacamp, Alison, Dataquest, Coursera), University program in Data Science, Machine Learning, AI, Comp Science',
       'University program in Data Science, Machine Learning, AI, Comp Science',
       'Self-taught/Bootcamp (including MOOCs e.g Datacamp, Alison, Dataquest, Coursera)',
       'University program in Data Science, Machine Learning, AI, Comp Science, University program in another discipline (e.g Economics, Monitoring and Evaluation etc)',
       'Self-taught/Bootcamp (including MOOCs e.g Datacamp, Alison, Dataquest, Coursera), University program in Data Science, Machine Learning, AI, Comp Science, University program in another discipline (e.g Economics, Monitoring and Evaluation etc)',
       'University program in another discipline (e.g Economics, Monitoring and Evaluation etc)',
       'None of the above'], dtype=object)

In [12]:
data.drop("Age",axis = 1,inplace = True)

In [13]:
data

,Gender,Country,Ocupation,HighestEducationLevel,Field,Company,Role,Are you working in a data-related capacity?,AI/ML/Ds,route,MainLanguage,Tools,Other,CodingPeriod,SpecialisedHardware,Which specialised hardware do you use?,skillset,Goals,What has been your biggest obstacle in doing your work in data/practicing as a data profession/pursuing a journey in data?,IntiativesDSZToTake
0,M,Zimbabwe,Unemployed,Bachelors,agriculture economics,NaN,NaN,No,No,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, R, SPSS/SAS",Excel,NaN,<1 year,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),internet,open more apprenticeship for data science
1,M,Zimbabwe,Formally employed,Bachelors,Software Engineering,Telecommunications,Software Developer,Sometimes,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, Other","Excel, Other",SQL,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Relevent Datasets,Competitions for solving local problems.
2,M,Zimbabwe,Formally employed,Bachelors,IT,Retail,IT Tech,No,Yes,"University program in Data Science, Machine Le...","Python, R",Excel,Power BI,<1 year,No,NaN,"Data visualisation, Computer Vision, Reinforce...",Certifications (online courses),Availability of local datasets,Training and seminars
3,M,Zimbabwe,University/College,GCE O/A Level,A level Sciences,NaN,NaN,Sometimes,NaN,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,1 - 5 years,No,NaN,Computer Vision,Certifications (online courses),Time management,Offer course with certification
4,M,Zimbabwe,Formally employed,Bachelors,Computer Information Systems,Solution Orientation,Software Engineer,No,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Knime/Weka/RapidMiner,NaN,>5 years,No,NaN,"Data visualisation, NLP",Certifications (online courses),Opportunities,Open source projects
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,F,Zimbabwe,University/College,Bachelors,Accounting,Auditing,Audit intern,No,No,Self-taught/Bootcamp (including MOOCs e.g Data...,R,Excel,NaN,1 - 5 years,No,NaN,Data visualisation,Certifications (online courses),Teaching myself,Seminars or workshops and invite beginners (li...
72,M,Zimbabwe,University/College,Bachelors,Informatics,Health,Systems Administrator,No,No,"University program in Data Science, Machine Le...",Python,Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Computer Vision, NLP, Tabu...",Certifications (online courses),Hardware Resources and Lack of Finances for Ce...,creating partnerships that may make certificat...
73,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Commerce,NGO,Province administration,Yes,Yes,None of the above,SPSS/SAS,Excel,NaN,<1 year,No,NaN,Tabular data,Certifications (online courses),Skill,"Offer more courses, bootcamps and meetups"
74,F,Zimbabwe,Unemployed,Bachelors,Mathematics,NaN,NaN,No,No,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,<1 year,No,NaN,Data visualisation,Certifications (online courses),Having to take time out for health reasons but...,Please keep sharing links to allow us to incre...
75,F,Zimbabwe,Formally employed,Bachelors,Statistics,Banking,Customer service advisor / Teller,No,No,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Other,SQL,<1 year,No,NaN,NaN,Certifications (online courses),Time,"Conduct trainings for data scientist, Conduct ..."

In [14]:
data.reset_index(drop=True,inplace=True)

In [15]:
DataSet1 = data[data.Gender == 'F']

In [16]:
DataSet2 = data[data.Gender == 'M']

In [17]:
DataSet1['Gender'].unique()

array(['F'], dtype=object)

In [18]:
DataSet2

,Gender,Country,Ocupation,HighestEducationLevel,Field,Company,Role,Are you working in a data-related capacity?,AI/ML/Ds,route,MainLanguage,Tools,Other,CodingPeriod,SpecialisedHardware,Which specialised hardware do you use?,skillset,Goals,What has been your biggest obstacle in doing your work in data/practicing as a data profession/pursuing a journey in data?,IntiativesDSZToTake
0,M,Zimbabwe,Unemployed,Bachelors,agriculture economics,NaN,NaN,No,No,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, R, SPSS/SAS",Excel,NaN,<1 year,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),internet,open more apprenticeship for data science
1,M,Zimbabwe,Formally employed,Bachelors,Software Engineering,Telecommunications,Software Developer,Sometimes,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, Other","Excel, Other",SQL,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Relevent Datasets,Competitions for solving local problems.
2,M,Zimbabwe,Formally employed,Bachelors,IT,Retail,IT Tech,No,Yes,"University program in Data Science, Machine Le...","Python, R",Excel,Power BI,<1 year,No,NaN,"Data visualisation, Computer Vision, Reinforce...",Certifications (online courses),Availability of local datasets,Training and seminars
3,M,Zimbabwe,University/College,GCE O/A Level,A level Sciences,NaN,NaN,Sometimes,NaN,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,1 - 5 years,No,NaN,Computer Vision,Certifications (online courses),Time management,Offer course with certification
4,M,Zimbabwe,Formally employed,Bachelors,Computer Information Systems,Solution Orientation,Software Engineer,No,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Knime/Weka/RapidMiner,NaN,>5 years,No,NaN,"Data visualisation, NLP",Certifications (online courses),Opportunities,Open source projects
5,M,Zimbabwe,Formally employed,Bachelors,Operations Research and Statistics,Law,Data Analyst,Yes,No,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, SPSS/SAS",Excel,NaN,<1 year,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Finding tutorials on coding,Teach data analysis or data science and offer ...
6,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Big data analytics,BI,BI Developer,Yes,No,"University program in Data Science, Machine Le...","Python, R, Other","Excel, Other",PowerBI,>5 years,No,NaN,Data visualisation,Certifications (online courses),Lack of data appreciation,Teach Zimbabwe that data is the new gold
7,M,Zimbabwe,Formally employed,Bachelors,Geographical information Science and Earth Obs...,Research institution,Scientist,Yes,Yes,"University program in Data Science, Machine Le...","Python, Javascript",Excel,NaN,<1 year,Yes,HPC,Data visualisation,Start a formal degree program (or college prog...,The field of data science is filled with noise...,Hold more bootcamps and masterclasses
9,M,Zimbabwe,Other,Diploma/National Certificate,Telecommunications,It,Customer Support,No,No,Self-taught/Bootcamp (including MOOCs e.g Data...,Other,Other,Power bi,<1 year,No,NaN,Data visualisation,Certifications (online courses),Unpaid /paid internships,More practical competitions or mentorship prog...
11,M,Zimbabwe,University/College,Masters/Postgrad Diploma,Bcom in Finance,Manufacturing and Distribution,Depot Supervisor,No,No,"University program in Data Science, Machine Le...","Python, R",Excel,NaN,<1 year,No,NaN,Data visualisation,Certifications (online courses),Looking for data,NaN
12,M,Zimbabwe,Other,Bachelors,BSc Computer Science Honours Degree,Remote IT support,NaN,NaN,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, Javascript, Other",Excel,NaN,1 - 5 years,No,NaN,Data visualisation,Certifications (online courses),High internet Cost and low electricity power s...,"Engage in more bootcamps, hackerthons problem ..."
13,M,Zimbabwe,Other,Masters/Postgrad Diploma,Data Science,Data Science,Convener,Sometimes,No,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, R, Other","Knime/Weka/RapidMiner, Other",Julia Language,>5 years,No,NaN,"Data visualisation, Computer Vision, NLP, Tabu...",Certifications (online courses),Economic environment,NaN
14,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Public Health,NGO,Strategic Information and Evaluation Manager,Yes,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,Other,Excel,NaN,1 - 5 years,Yes,Power BI,Data visualisation,Certifications (online courses),People don't want to use data for decision making,Introductory seminars in colleges
15,M,Zimbabwe,Formally employed,Diploma/National Certificate,Telecommunications,Mining,Emergency coordinator,No,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, R",Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Computer Vision",Certifications (online courses),Finance,NaN
18,M,Zimbabwe,University/College,Bachelors,Honors degree in Informatics,ICT,System architect,Sometimes,No,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,<1 year,No,NaN,Data visualisation,Certifications (online courses),No easy access to local data for example it's ...,Awareness campaigns for industry to realize th...
19,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Big Data Analytics,IT,Data Analyst,Yes,Yes,"University program in Data Science, Machine Le...","Python, R",Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, NLP, Reinforcement Learning",Certifications (online courses),Lack of finances to do certifications as no on...,I think they should do physical and virtual bo...
20,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Leadership,3rd sector,Advisor,Yes,Yes,University program in another discipline (e.g ...,SPSS/SAS,Excel,NaN,<1 year,Yes,NaN,Data visualisation,Certifications (online courses),Lack of local institutions providing data scie...,NaN
21,M,Zimbabwe,University/College,GCE O/A Level,NaN,NaN,NaN,No,NaN,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Computer Vision, NLP, Tabu...",Certifications (online courses),Lack of entry level opportunities in Zimbabwe,"Hosting hackathons & meetups, building communi..."
22,M,Zimbabwe,University/College,Bachelors,Data Analytics,NaN,NaN,Sometimes,NaN,"University program in Data Science, Machine Le...","Python, R",Excel,NaN,1 - 5 years,No,NaN,Data visualisation,Certifications (online courses),failing to master Data Cleaning,NaN
24,M,Zimbabwe,Formally employed,Bachelors,BSc Honors in Informatics,Insurance,System Engineer,Sometimes,Yes,"University program in Data Science, Machine Le...",Python,Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Reinforcement Learning",Certifications (online courses),Lack of Opportunities,Bootcamps
25,M,Zimbabwe,University/College,Bachelors,Statistics,Data analysis,Data analyst,Yes,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, R, SPSS/SAS",Excel,NaN,<1 year,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Time,Promote data science webinars and conferences
31,M,Zimbabwe,Formally employed,Bachelors,Information Systems,NGO,MIS Officer,Yes,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,Other,Excel,NaN,<1 year,No,NaN,"Data visualisation, Tabular data",Start a formal degree program (or college prog...,Choosing the best tool for data visualisation,Teach people code
32,M,Zimbabwe,University/College,Diploma/National Certificate,Data science,Data analyst /scientist,Data scientist,Yes,Yes,"University program in Data Science, Machine Le...",Python,Excel,Power bi,1 - 5 years,No,No,Data visualisation,Start a formal degree program (or college prog...,Nothing much,I will help the organization to grow in their ...
33,M,Zimbabwe,University/College,Bachelors,Computer Science,"Information, Communication and Technology",Data analyst,No,Yes,"University program in Data Science, Machine Le...",Python,"Excel, Other","Power Bi, Qlik Sense",1 - 5 years,No,NaN,"Data visualisation, Computer Vision, NLP",Start a formal degree program (or college prog...,Data,Government assistance
34,M,Zimbabwe,Unemployed,Bachelors,IT,NaN,NaN,NaN,NaN,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,<1 year,No,NaN,"Data visualisation, Computer Vision",Certifications (online courses),Limited resources,To have innovation hub
35,M,Zimbabwe,Formally employed,Bachelors,Operations Research And Statistics,Transport and Logistics,Fleet Controller,Sometimes,Yes,"University program in Data Science, Machine Le...","Python, SPSS/SAS, Other","Excel, Other",Rstudio,<1 year,No,NaN,Data visualisation,Start a formal degree program (or college prog...,"Lack of enough experience ,",Introduce data science to companies so that th...
36,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Information Technology,Aviation,Senior Systems Support Officer,Yes,No,"University program in Data Science, Machine Le...","Python, R","Excel, Other",SQL Server,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Managing both full-time employment as well as ...,NaN
38,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,ICT,Humanitarian Work,Data Analyst,Yes,Yes,"University program in Data Science, Machine Le...","Python, SPSS/SAS",Excel,NaN,<1 year,No,NaN,Data visualisation,Start a formal degree program (or college prog...,Inability by management to realise the importa...,NaN
40,M,Zimbabwe,Unemployed,Masters/Postgrad Diploma,Masters in data science and informatics,Analyst,NaN,Yes,No,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, R, SPSS/SAS, Other","Excel, Other",Power bi,1 - 5 years,No,NaN,"Data visualisation, Computer Vision, NLP, Rein...",Certifications (online courses),License for other packages eg Google ip for R ...,To have sponsered programs for data science
41,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,"Economics, Big Data Analytics",Telecoms,Data scientist,Yes,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, R",Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, NLP, Reinforcement Learnin...",Certifications (online courses),Specialised hardware,NaN
42,M,Zimbabwe,Formally employed,Diploma/National Certificate,Computer Studies,Health Research,Database Administrator,Yes,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,Other,"Excel, Other",Stata,>5 years,No,None,"Data visualisation, Tabular data",Start a formal degree program (or college prog...,Finances,Have more workshops in Zim where we will meet
44,M,Zimbabwe,University/College,GCE O/A Level,Information Science and technology,NaN,NaN,No,NaN,"University program in Data Science, Machine Le...","Python, R",Excel,NaN,<1 year,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Not knowing where to start and the path to take,To engage us more on how to begin this data sc...
45,M,zimbabwe,University/College,Masters/Postgrad Diploma,M&E,health,supportt,No,Yes,"University program in Data Science, Machine Le...",SPSS/SAS,Excel,NaN,<1 year,No,NaN,"Data visualisation, Tabular data",Start a formal degree program (or college prog...,entry level jobs,mentoship
46,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Health Economics,ZIMSTAT,Statistician,Yes,Yes,"University program in Data Science, Machine Le...","Python, R, Matlab, SPSS/SAS",Excel,Minitab,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),NaN,NaN
47,M,Zimbabwe,Formally employed,Bachelors,IT,IT,Management Information Systems Analyst,Yes,Yes,"University program in Data Science, Machine Le...",SPSS/SAS,Excel,NaN,<1 year,No,NaN,Tabular data,Certifications (online courses),Achieving speed and accuracy,NaN
48,M,Zimbabwe,University/College,Bachelors,Mathematics,NaN,NaN,No,NaN,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,<1 year,No,NaN,Data visualisation,Certifications (online courses),Internship,Mentorship and Intership
50,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Geospatial Science,Power utility Company,GIS Analysist,Yes,Yes,University program in another discipline (e.g ...,"Python, R",Excel,NaN,1 - 5 years,Yes,omen laptop 17t-cb100,"Data visualisation, Tabular data",Nothing,Reliable internet access,Increase in meetup and social informal gatheri...
53,M,Zimbabwe,Formally employed,Bachelors,Operations Research and Statistics,Database management and analysis,Monitoring and Evaluation Intern,Yes,No,Self-taught/Bootcamp (including MOOCs e.g Data...,"R, SPSS/SAS",Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Computer Vision, Tabular data",Start a formal degree program (or college prog...,Access to proper data handling softwares,3-5 day training courses\nShort courses certif...
54,M,Zimbabwe,University/College,Diploma/National Certificate,Monitoring and Evaluation,NGO,Monitoring and Evaluation Officer,Yes,No,Self-taught/Bootcamp (including MOOCs e.g Data...,"R, SPSS/SAS",Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),"Equipment, computers",Go around Universities having data science clubs
56,M,ZImbabwe,Formally employed,Bachelors,NaN,NaN,NaN,No,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, R",Excel,NaN,1 - 5 years,Yes,GPU,"Data visualisation, Tabular data",Certifications (online courses),FInancing,NaN
57,M,Zimbabwe - sadly,Formally employed,Diploma/National Certificate,architect,cyber,Cloud Platform Developer,Sometimes,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Finances - economy in zimbabwe,NaN
58,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Mathematics,Teaching,Teacher,Sometimes,No,Self-taught/Bootcamp (including MOOCs e.g Data...,R,Excel,NaN,<1 year,No,NaN,Data visualisation,Certifications (online courses),Exposure on data to work with.access to practi...,Provide online courses.provide practical probl...
59,M,Scotland,Formally employed,Masters/Postgrad Diploma,Computational Mathematics,Asset Management,Analytics Associate,Yes,Yes,Self-taught/Bootcamp (including MOOCs e.g Data...,"Python, R, Other","Excel, Other",Power BI and VBA,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Company not able to be democratic in technology,Encourage APPLIED Data Sciences. Make Data Sci...
60,M,Zimbabwe,University/College,GCE O/A Level,NaN,NaN,Intern,Sometimes,Yes,"University program in Data Science, Machine Le...","Python, R, SPSS/SAS",Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Little data to work with,Offer mentorship programs. Hosting competition...
61,M,Equatorial Guinea,Formally employed,Masters/Postgrad Diploma,Masters,NGO,Health information systems advisor,Yes,Yes,"University program in Data Science, Machine Le...","Python, R, SPSS/SAS","Excel, Other",NaN,>5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Data quality,Engage in group data science projects
62,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Big Data Analytics,NGO,IT Officer,Sometimes,No,"University program in Data Science, Machine Le...","Python, R, SPSS/SAS","Excel, Other","STATA, Power Bi",>5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Non alignment of current work with current stu...,Regular sharing of an updated list of data ana...
63,M,SA,University/College,Bachelors,Bsc.Eng Electrical and Computer Engineering,Digital Product Agency - Software Engineering ...,Jnr Software Engineer,Sometimes,No,"University program in Data Science, Machine Le...",Python,NaN,NaN,<1 year,Yes,Nvidia Cuda,"Reinforcement Learning, Tabular data",Nothing,Real life problems to solve that yield tangibl...,Build an ACTIVE community even over whatsapp.
65,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Data Analytics & Corp Gov,Insurance,Client Services Manager,Sometimes,Yes,"University program in Data Science, Machine Le...","Python, SPSS/SAS","Excel, Other",PowerBI,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Nothing,A job directly,Collaborate with Universities by hosting moreb...
66,M,Zimbabwe,Unemployed,Masters/Postgrad Diploma,Agricultural and Applied Economics,NaN,NaN,Yes,NaN,Self-taught/Bootcamp (including MOOCs e.g Data...,R,Excel,Stata,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Certifications (online courses),Lack of exposure,Open a free platform for people to interact
67,M,Zimbabwe,Formally employed,Diploma/National Certificate,IT,Accounting and Audit,IT consultant,Sometimes,No,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Tabular data",Start a formal degree program (or college prog...,Management under scores the need for Data scie...,NaN
68,M,Zimbabwe,Formally employed,Bachelors,Information Systems,Telco,Data Analytics Manager,Yes,Yes,"University program in Data Science, Machine Le...","Python, R, Javascript, Matlab, SPSS/SAS, Other","Excel, Knime/Weka/RapidMiner",NaN,>5 years,No,NaN,"Data visualisation, Reinforcement Learning, Ta...",Certifications (online courses),NaN,More hands on workshops and mentorship
70,M,South Africa,Formally employed,Bachelors,Business management and information technology,Telecommunications,Technical support,Sometimes,No,Self-taught/Bootcamp (including MOOCs e.g Data...,Python,Excel,NaN,<1 year,No,NaN,Data visualisation,Certifications (online courses),Long distance learning,Long distance learning
72,M,Zimbabwe,University/College,Bachelors,Informatics,Health,Systems Administrator,No,No,"University program in Data Science, Machine Le...",Python,Excel,NaN,1 - 5 years,No,NaN,"Data visualisation, Computer Vision, NLP, Tabu...",Certifications (online courses),Hardware Resources and Lack of Finances for Ce...,creating partnerships that may make certificat...
73,M,Zimbabwe,Formally employed,Masters/Postgrad Diploma,Commerce,NGO,Province administration,Yes,Yes,None of the above,SPSS/SAS,Excel,NaN,<1 year,No,NaN,Tabular data,Certifications (online courses),Skill,"Offer more courses, bootcamps and meetups"